CREATE TABLE IF NOT EXISTS user_tb (
    id SERIAL PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    roles PRIORIDADES NOT NULL,
    created_account TIMESTAMP WITH TIMEZONE
);